app:
  encryption_key: "LocalEncrypionKey"
# user-session add configs
  auth_type: "jwttoken"
log4js:
  appenders:
    default:
      type: "console"
  categories:
    default:
      appenders: ["default"]
      level: "debug"
    system:
      appenders: ["default"]
      level: "debug"
    access:
      appenders: ["default"]
      level: "debug"
    error:
      appenders: ["default"]
      level: "debug"
dodai:
  app_id: "a_jf02fuwj"
  group_id: "g_HfrQEfKt"
  app_key: "akey_0lzw5aU3DOyYMzaBAX"
  root_key: "rkey_wQ33ngqWBD5LiDU5Xm"
  schema: "https"
  host: "st-dod.riiiver.com"
  appId : "a_jf02fuwj"
  groupId: "g_HfrQEfKt"
  rootkey: "rkey_wQ33ngqWBD5LiDU5Xm"

region: 
  LIST: 
    - name: 
        ja: "アメリカ合衆国"
        en: "United States"
      region: US
    - name: 
        ja: "日本"
        en: "Japan"
      region: JP
  JP: 
    cognito: cognito_jp
    cognito_bb: cognito_jp
    mysql: mysql_jp
    mysql_read: mysql_jp
  US: 
    cognito: cognito_us
    cognito_bb: cognito_us
    mysql: mysql_us
    mysql_read: mysql_us

# applet:
#   url_add_free_applet: "http://localhost/applet/add_free_applet"
#   url_remove_free_applet: "http://localhost/applet/remove_free_applet"
#   url_nice_applet: "http://localhost/applet/nice_applet"
#   url_cancel_nice_applet: "http://localhost/applet/cancel_nice_applet"
cognito_jp:
  region: "ap-northeast-1"
  userpool: "ap-northeast-1_qikw6HlIX"
  clientId: "6rcvfmhannugn8jhsn5vahk8a6"
  AWSAccessKey: "AKIAIYJB7EC6DTXMNUPQ"
  AWSSecretKey: "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"
cognito_us: 
  region: "us-west-2"
  userpool: "us-west-2_wQLQUarYb"
  clientId: "2cok9q27dqcj7b6e44a6n272pb"
  AWSAccessKey: "AKIAIYJB7EC6DTXMNUPQ"
  AWSSecretKey: "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"
mysql_jp:
  host: "localhost"
  user: "root"
  password: "14041998"
  db: "riuser_stg_jp"
  limit: 20
mysql_us:
  host: "localhost"
  user: "root"
  password: "14041998"
  db: "riuser_stg_us"
  limit: 20
google:
  aud: [
        "559411539788-gp138q93o68fdiklnu3dgmnmmjroafan.apps.googleusercontent.com",
        "559411539788-id91omtt4ob5deq7131850r6jk88hvgm.apps.googleusercontent.com",
        "559411539788-i8udibkfvpid90ivrou35bg952p06fo3.apps.googleusercontent.com"
       ]
Store:
  url: "https://st-str.riiiver.com/api/store/top/"
  top: "https://st-str.riiiver.com/store_top/"
  logout: "https://st-str.riiiver.com/login?redirect_uri=https%3A%2F%2Fst-str.riiiver.com%2Fstore_top%2F&css=s"
  resourceUrl: "https://st-str.riiiver.com/static/img"
  menuUrl: "https://st-str.riiiver.com/store_menu/"
  termsOfService: "https://st-str.riiiver.com/store_tos/?erst_footer=0"
  key: ""
  cert: ""
  keyid: "7u6imvbso5o61fup33qlvbfs0b"

SessionCheck : api
User:
  host: "https://st-str.riiiver.com"
  HmacSecret: "1lf3oumldqtgbso5o61fup33ql" 

riiiverdb:
  AWS_ACCESS_KEY: "AKIAIYJB7EC6DTXMNUPQ"
  AWS_SECRET_KEY: "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"
  CREDENTIAL: "rkey_wQ33ngqWBD5LiDU5Xm"
  buckets:
    appletIcon:  'st-riiiver-jp'
    blockIcon:   'st-riiiver-jp'
    blockIllust: 'st-riiiver-jp'
    blockLambda: 'st-riiiver-jp'
  s3_region: 's3-ap-northeast-1'
  REGION: 'JP'

# user-session config END
Push:
  production: false

