FROM mysql:8.0
ENV HOME /root
# ENV MYSQL_ALLOW_EMPTY_PASSWORD yes
ENV MYSQL_ROOT_PASSWORD test
EXPOSE 3306

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-get update
# RUN add-apt-repository ppa:phpmyadmin/ppa
RUN apt install -y php libapache2-mod-php
# RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 2EA3055293CB3F45
# RUN apt-get update
RUN apt install -y apache2
## for apt to be noninteractive
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

## preesed tzdata, update package index, upgrade packages and install needed software
RUN echo "tzdata tzdata/Areas select Europe" > /tmp/preseed.txt; \
    echo "tzdata tzdata/Zones/Europe select Berlin" >> /tmp/preseed.txt; \
    debconf-set-selections /tmp/preseed.txt && \
    apt-get update && \
    apt-get install -y tzdata

RUN echo "deb http://deb.debian.org/debian stretch main" >> /etc/apt/sources.list
RUN echo "deb-src http://deb.debian.org/debian stretch main" >> /etc/apt/sources.list

RUN echo "deb http://deb.debian.org/debian stretch-updates main" >> /etc/apt/sources.list
RUN echo "deb-src http://deb.debian.org/debian stretch-updates main" >> /etc/apt/sources.list

RUN echo "deb http://security.debian.org/debian-security/ stretch/updates main" >> /etc/apt/sources.list
RUN echo "deb-src http://security.debian.org/debian-security/ stretch/updates main" >> /etc/apt/sources.list


RUN apt update
RUN apt-get  upgrade -y
RUN apt install -y phpmyadmin
RUN ln -s /etc/phpmyadmin/apache.conf /etc/apache2/conf-available/phpmyadmin.conf
RUN a2enconf phpmyadmin.conf
COPY initilizeDB.sql  /docker-entrypoint-initdb.d/initilizeDB.sql