source applet.sql
source appletgoodnum.sql
source appletmisc.sql
source appletpublicstatus.sql
source appletstorestatus.sql
source applicationAPIAuth.sql
source block.sql
source blockStoreStatus.sql
source blockLambdaStatus.sql
source clientAPIAuth.sql
source notificationToke.sql

source app_version.sql
source applet_category.sql
source applet_set.sql
source applet_slot.sql
source applet_table.sql
source data_applet.sql
source data_user.sql
source data_watch_status.sql
source pushinfo.sql
source pushtoken.sql
source watch_device.sql
source watch_firmware.sql
source watch_status.sql
